export const paperStyle = {margin : 'auto' , width : '95%' }
export const containerStyle ={margin : 'auto' , width : '97%'}
export const cellStyle ={ display : 'flex' , alignItems : 'center' , justifyContent : 'center',  color: 'fff',fontSize:'16px'}
export const formStyle = { p: '2px 4px', display: 'flex', alignItems: 'center', width: 270  , marginRight : '10px'}
export const categoryBox ={ width: 280 , marginRight : '10px' }
export const subCategoryBox ={ width: 280}
export const repairBox ={ width: 240}
export const addButton = {marginLeft : '1rem', width :'5rem' , height:'1.5rem'}
export const add = {marginLeft : '7rem', width :'7rem' , height:'2.5rem'}
export const statusButton = {marginLeft : '1rem', width :'8rem' , height:'2rem'}
export const addIcon = {color:'#fff' , marginTop:'18px'}
export const headingStyle = {marginRight : '10px' ,fontWeight : 'bold'}
export const boxStyle = { display : 'flex' , margin : 'auto' , width : '97%' , alignItems: 'center'}
export const backIconStyle  ={width :'20px', height:'15px'}
export const cancelButton = {height :'37px' ,marginLeft:'10px' , fontSize :'12px', marginLeft:'63rem', marginTop:'10px'}
export const saveButton = {height :'37px' ,marginLeft:'10px' , fontSize :'14px',marginTop:'10px'}
export const dividerStyle = {marginTop: '20px' , marginBottom :'20px'}
export const mainBox = {margin : 'auto' , width : '90%' }
export const innerBox = {display : "flex" , flexDirection : "row" ,justifyContent:'space-between', width:'62%'}
export const descBox = {display : "flex" , flexDirection : "Column" ,justifyContent:'space-evenly', width:'74%'}
export const data = {display : "flex" , flexDirection : "row" ,justifyContent:'space-evenly', width:'80%'}
export const detailIcon = {height :'35px', maxWidth :'10%', marginLeft:'70rem', marginTop:'10px'}