export const paperStyle = {margin : 'auto' , width : '95%' }
export const containerStyle ={margin : 'auto' , width : '97%' }
export const cellStyle ={ display : 'flex' , alignItems : 'center' , justifyContent : 'center',  color: 'fff',fontSize:'16px'}
export const headingStyle = {marginRight : '10px' ,fontWeight : 'bold'}
export const formStyle = { p: '2px 4px', display: 'flex', alignItems: 'center', width: 270  , marginRight : '10px'}
export const buttonStyle = {marginLeft : '23rem', width :'140px' , height:'37px'}
export const iconStyle = {color:'#fff' , marginTop:'18px',marginLeft:'5px' , marginRight:'-5px'}
export const boxStyle = { display : 'flex' , margin : 'auto' , width : '97%' }
export const backIconStyle ={width :'20px', height:'15px',marginTop:'28px'}
export const cancelButton ={height :'37px' ,marginLeft:'10px' , fontSize :'12px', marginLeft:'47rem', marginTop:'10px' , color:'#6a6a6a'}
export const saveButton = {height :'37px' ,marginLeft:'10px' , fontSize :'12px',marginTop:'10px'}
export const photoIcon ={ width : '15%', height :'7rem' ,color :"#D3D3D"}
export const attchmentPhoto ={width : '10%', height :'3rem' ,color :"#D3D3D3"}
export const uploadButton = {width :'75px' , height :'35px',marginLeft:'1rem' ,marginTop :'-20px',fontSize:'10px'}
export const uploadIcon ={color: '#fff' ,marginLeft :'2px', marginBottom : '-18px' ,marginRight:'-5px'}
export const dividerStyle = {marginTop: '10px' , marginBottom :'10px'}
export const divider = {marginTop: '20px' , marginBottom :'20px'}
export const mainBox = {margin : 'auto' , width : '90%' }
export const innerBox = {display : "flex" , flexDirection : "row" ,justifyContent:'space-between', width:'62%'}
